project:
  type: book
  output-dir: ../docs
book:
  title: Open textbooks with Quarto on GitHub Pages
  author: Research Data Management Support
  date: last-modified
  favicon: img/favicon.ico
  search: true
  sidebar:
    logo: "https://utrechtuniversity.github.io/workshop-reproducible-manuscripts/images/quarto-hex-logo.png"
  repo-url: https://github.com/UtrechtUniversity/quarto-github-textbooks/
  repo-actions: [edit, issue]
  back-to-top-navigation: true
  page-footer: 
    center: "Created by Research Data Management Support, Utrecht University, The Netherlands"
  chapters:
  - index.qmd
  - part: Basic set-up
    chapters:
    - prerequisites.qmd
    - get-started.qmd
    - markdown.qmd
    - git.qmd
  - part: Customization
    chapters:
    - quarto-settings.qmd
    - multimedia.qmd
    - interactivity.qmd
    - styling.qmd
    - citation.qmd
  - part: Publishing
    chapters:
    - rendering.qmd
    - archiving.qmd
  - references.qmd
bibliography: references.bib
engine: knitr
format:
  html:
    theme: cosmo
    css: include/webex.css
    include-after-body: include/webex.js
    link-external-icon: true
    link-external-newwindow: true
    other-links:
      - text: "Research Data Management Support (Utrecht University)"
        icon: info
        href: https://uu.nl/rdm/
        target: "_blank"
    code-links:
      - repo: "https://github.com/UtrechtUniversity/quarto-github-textbooks/"
